service: cnx-dealers

package:
  individually: true
  exclude:
    - .eslintrc.json
    - .git/**
    - .gitignore
    - tests/**

plugins:
  - serverless-bundle

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2
  runtime: nodejs12.x
  timeout: 30

functions:
  - ${file(resources/functions/get-dealers.yml)}
  - ${file(resources/functions/get-vehicles-by-bac.yml)}

resources:
